In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
from scipy.stats import randint, uniform
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB 
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier


In [2]:
df = pd.read_csv('phishing.csv')
df.head()

url  length_url  \
0              http://www.crestonwood.com/router.php          37   
1  http://shadetreetechnology.com/V4/validation/a...          77   
2  https://support-appleld.com.secureupdate.duila...         126   
3                                 http://rgipt.ac.in          18   
4  http://www.iracing.com/tracks/gateway-motorspo...          55   

   length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  nb_or  ...  \
0               19   0        3           0      0      0       0      0  ...   
1               23   1        1           0      0      0       0      0  ...   
2               50   1        4           1      0      1       2      0  ...   
3               11   0        2           0      0      0       0      0  ...   
4               15   0        2           2      0      0       0      0  ...   

   domain_in_title  domain_with_copyright  whois_registered_domain  \
0                0                      1                        0   
1                1                      0                        0   
2                1                      0                        0   
3                1                      0                        0   
4                0                      1                        0   

   domain_registration_length  domain_age  web_traffic  dns_record  \
0                          45          -1            0           1   
1                          77        5767            0           0   
2                          14        4004      5828815           0   
3                          62          -1       107721           0   
4                         224        8175         8725           0   

   google_index  page_rank      status  
0             1          4  legitimate  
1             1          2    phishing  
2             1          0    phishing  
3             0          3  legitimate  
4             0          6  legitimate  

[5 rows x 89 columns]

In [3]:
print(df.shape)

(11430, 89)


In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11430 entries, 0 to 11429
Data columns (total 89 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   url                         11430 non-null  object 
 1   length_url                  11430 non-null  int64  
 2   length_hostname             11430 non-null  int64  
 3   ip                          11430 non-null  int64  
 4   nb_dots                     11430 non-null  int64  
 5   nb_hyphens                  11430 non-null  int64  
 6   nb_at                       11430 non-null  int64  
 7   nb_qm                       11430 non-null  int64  
 8   nb_and                      11430 non-null  int64  
 9   nb_or                       11430 non-null  int64  
 10  nb_eq                       11430 non-null  int64  
 11  nb_underscore               11430 non-null  int64  
 12  nb_tilde                    11430 non-null  int64  
 13  nb_percent                  114

In [5]:
print(df.columns)

Index(['url', 'length_url', 'length_hostname', 'ip', 'nb_dots', 'nb_hyphens',
       'nb_at', 'nb_qm', 'nb_and', 'nb_or', 'nb_eq', 'nb_underscore',
       'nb_tilde', 'nb_percent', 'nb_slash', 'nb_star', 'nb_colon', 'nb_comma',
       'nb_semicolumn', 'nb_dollar', 'nb_space', 'nb_www', 'nb_com',
       'nb_dslash', 'http_in_path', 'https_token', 'ratio_digits_url',
       'ratio_digits_host', 'punycode', 'port', 'tld_in_path',
       'tld_in_subdomain', 'abnormal_subdomain', 'nb_subdomains',
       'prefix_suffix', 'random_domain', 'shortening_service',
       'path_extension', 'nb_redirection', 'nb_external_redirection',
       'length_words_raw', 'char_repeat', 'shortest_words_raw',
       'shortest_word_host', 'shortest_word_path', 'longest_words_raw',
       'longest_word_host', 'longest_word_path', 'avg_words_raw',
       'avg_word_host', 'avg_word_path', 'phish_hints', 'domain_in_brand',
       'brand_in_subdomain', 'brand_in_path', 'suspecious_tld',
       'statistical_report', 

In [6]:
df.isnull()


url  length_url  length_hostname     ip  nb_dots  nb_hyphens  nb_at  \
0      False       False            False  False    False       False  False   
1      False       False            False  False    False       False  False   
2      False       False            False  False    False       False  False   
3      False       False            False  False    False       False  False   
4      False       False            False  False    False       False  False   
...      ...         ...              ...    ...      ...         ...    ...   
11425  False       False            False  False    False       False  False   
11426  False       False            False  False    False       False  False   
11427  False       False            False  False    False       False  False   
11428  False       False            False  False    False       False  False   
11429  False       False            False  False    False       False  False   

       nb_qm  nb_and  nb_or  ...  domain_in_title  domain_with_copyright  \
0      False   False  False  ...            False                  False   
1      False   False  False  ...            False                  False   
2      False   False  False  ...            False                  False   
3      False   False  False  ...            False                  False   
4      False   False  False  ...            False                  False   
...      ...     ...    ...  ...              ...                    ...   
11425  False   False  False  ...            False                  False   
11426  False   False  False  ...            False                  False   
11427  False   False  False  ...            False                  False   
11428  False   False  False  ...            False                  False   
11429  False   False  False  ...            False                  False   

       whois_registered_domain  domain_registration_length  domain_age  \
0                        False                       False       False   
1                        False                       False       False   
2                        False                       False       False   
3                        False                       False       False   
4                        False                       False       False   
...                        ...                         ...         ...   
11425                    False                       False       False   
11426                    False                       False       False   
11427                    False                       False       False   
11428                    False                       False       False   
11429                    False                       False       False   

       web_traffic  dns_record  google_index  page_rank  status  
0            False       False         False      False   False  
1            False       False         False      False   False  
2            False       False         False      False   False  
3            False       False         False      False   False  
4            False       False         False      False   False  
...            ...         ...           ...        ...     ...  
11425        False       False         False      False   False  
11426        False       False         False      False   False  
11427        False       False         False      False   False  
11428        False       False         False      False   False  
11429        False       False         False      False   False  

[11430 rows x 89 columns]

In [7]:
df.isnull().sum()
      

url                0
length_url         0
length_hostname    0
ip                 0
nb_dots            0
                  ..
web_traffic        0
dns_record         0
google_index       0
page_rank          0
status             0
Length: 89, dtype: int64

In [8]:
df.isnull().sum().sum()

0

In [9]:
print(df['status'].value_counts())

legitimate    5715
phishing      5715
Name: status, dtype: int64


In [10]:
mapping = {'legitimate': 0, 'phishing': 1}
df['status'] = df['status'].map(mapping)

In [11]:
print(df['status'].unique())

[0 1]


In [12]:
print(df['url'].unique())
print(df['length_url'].unique())

['http://www.crestonwood.com/router.php'
 'http://shadetreetechnology.com/V4/validation/a111aedc8ae390eabcfa130e041a10a4'
 'https://support-appleld.com.secureupdate.duilawyeryork.com/ap/89e6a3b4b063b8d/?cmd=_update&dispatch=89e6a3b4b063b8d1b&locale=_'
 ...
 'https://www.facebook.com/Interactive-Television-Pvt-Ltd-Group-M-100230523435650/photos/?ref=page_internal'
 'http://www.mypublicdomainpictures.com/'
 'http://174.139.46.123/ap/signin?openid.pape.max_auth_age=0&amp;openid.return_to=https%3A%2F%2Fwww.amazon.co.jp%2F%3Fref_%3Dnav_em_hd_re_signin&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.assoc_handle=jpflex&amp;openid.mode=checkid_setup&amp;key=a@b.c&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;&amp;ref_=nav_em_hd_clc_signin']
[  37   77  126   18   55   32   19   81   42  104   56   43   83   31
   25   51   50   34   27   63   66   4

In [13]:
corr_matrix = df.corr()
print(corr_matrix)

                 length_url  length_hostname        ip   nb_dots  nb_hyphens  \
length_url         1.000000         0.223025  0.453961  0.443589    0.399564   
length_hostname    0.223025         1.000000  0.252013  0.408956    0.057702   
ip                 0.453961         0.252013  1.000000  0.288398    0.109860   
nb_dots            0.443589         0.408956  0.288398  1.000000    0.045099   
nb_hyphens         0.399564         0.057702  0.109860  0.045099    1.000000   
...                     ...              ...       ...       ...         ...   
web_traffic        0.072205         0.163238  0.167930  0.087969   -0.041464   
dns_record         0.023357        -0.023344  0.127823  0.126659   -0.031477   
google_index       0.236395         0.213990  0.270743  0.209616   -0.018828   
page_rank         -0.102582        -0.159342 -0.218968 -0.097312    0.104341   
status             0.248580         0.238322  0.321698  0.207029   -0.100107   

                    nb_at     nb_qm    

In [14]:
target_corr = corr_matrix['status']
print(target_corr)

length_url         0.248580
length_hostname    0.238322
ip                 0.321698
nb_dots            0.207029
nb_hyphens        -0.100107
                     ...   
web_traffic        0.060388
dns_record         0.122119
google_index       0.731171
page_rank         -0.511137
status             1.000000
Name: status, Length: 88, dtype: float64


In [15]:
threshold = 0.1
relevant_features = target_corr[abs(target_corr) > threshold].index.tolist()
print(relevant_features)

['length_url', 'length_hostname', 'ip', 'nb_dots', 'nb_hyphens', 'nb_at', 'nb_qm', 'nb_and', 'nb_eq', 'nb_slash', 'nb_semicolumn', 'nb_www', 'nb_com', 'https_token', 'ratio_digits_url', 'ratio_digits_host', 'tld_in_subdomain', 'abnormal_subdomain', 'nb_subdomains', 'prefix_suffix', 'shortening_service', 'length_words_raw', 'shortest_word_host', 'longest_words_raw', 'longest_word_host', 'longest_word_path', 'avg_words_raw', 'avg_word_host', 'avg_word_path', 'phish_hints', 'suspecious_tld', 'statistical_report', 'nb_hyperlinks', 'ratio_intHyperlinks', 'ratio_extRedirection', 'external_favicon', 'links_in_tags', 'ratio_intMedia', 'ratio_extMedia', 'safe_anchor', 'empty_title', 'domain_in_title', 'domain_with_copyright', 'domain_registration_length', 'domain_age', 'dns_record', 'google_index', 'page_rank', 'status']


In [16]:
# Select the desired attributes along with the target variable
selected_columns = relevant_features
df = df[relevant_features]

In [17]:
for col in relevant_features:
    label_encoder = LabelEncoder()
    df[col] = label_encoder.fit_transform(df[col])


In [18]:
X = df[relevant_features].drop('status', axis=1)
y = df['status']

In [19]:
#Random Forest
test_ratios = [0.1,0.2, 0.3, 0.4,0.5,0.6,0.7,0.8,0.9]

for test_ratio in test_ratios:
    print(f"Test Ratio: {test_ratio}")
    
    # Split the dataset into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_ratio, random_state=42)
    
    # Train the Random Forest Classifier
    rf = RandomForestClassifier()
    rf.fit(X_train, y_train)
    
    # Predict on the test data
    rf_predict = rf.predict(X_test)
    
    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, rf_predict)
    precision_legit = precision_score(y_test, rf_predict, pos_label=0)*100
    precision_phish = precision_score(y_test, rf_predict, pos_label=1)*100
    recall_legit = recall_score(y_test, rf_predict, pos_label=0)*100
    recall_phish = recall_score(y_test, rf_predict, pos_label=1)*100
    f1_legit = f1_score(y_test, rf_predict, pos_label=0)*100
    f1_phish = f1_score(y_test, rf_predict, pos_label=1)*100
    cm = confusion_matrix(y_test, rf_predict)

    # Convert accuracy to percentage
    accuracy_percentage = accuracy * 100
    
    # Print results for legitimate class
    print("Results for Legitimate class:")
    print("Accuracy:", accuracy_percentage, "%")
    print("Precision:", precision_legit,"%")
    print("Recall:", recall_legit,"%")
    print("F1 Score:", f1_legit,"%")
    print("Confusion Matrix:")
    print(cm)
    print()
    
    # Print results for phishing class
    print("Results for Phishing class:")
    print("Accuracy:", accuracy_percentage, "%")
    print("Precision:", precision_phish,"%")
    print("Recall:", recall_phish,"%")
    print("F1 Score:", f1_phish,"%")
    print("Confusion Matrix:")
    print(cm)
    print()


Test Ratio: 0.1
Results for Legitimate class:
Accuracy: 97.3753280839895 %
Precision: 96.95431472081218 %
Recall: 97.94871794871794 %
F1 Score: 97.44897959183673 %
Confusion Matrix:
[[573  12]
 [ 18 540]]

Results for Phishing class:
Accuracy: 97.3753280839895 %
Precision: 97.82608695652173 %
Recall: 96.7741935483871 %
F1 Score: 97.2972972972973 %
Confusion Matrix:
[[573  12]
 [ 18 540]]

Test Ratio: 0.2
Results for Legitimate class:
Accuracy: 96.63167104111986 %
Precision: 95.99659284497444 %
Recall: 97.40708729472775 %
F1 Score: 96.69669669669669 %
Confusion Matrix:
[[1127   30]
 [  47 1082]]

Results for Phishing class:
Accuracy: 96.63167104111986 %
Precision: 97.3021582733813 %
Recall: 95.837023914969 %
F1 Score: 96.5640339134315 %
Confusion Matrix:
[[1127   30]
 [  47 1082]]

Test Ratio: 0.3
Results for Legitimate class:
Accuracy: 96.3254593175853 %
Precision: 95.88571428571429 %
Recall: 96.88221709006929 %
F1 Score: 96.38139000574384 %
Confusion Matrix:
[[1678   54]
 [  72 1625]]

In [20]:
#SVM
test_ratios = [0.1,0.2, 0.3, 0.4,0.5,0.6,0.7,0.8,0.9]

for test_ratio in test_ratios:
    print(f"Test Ratio: {test_ratio}")
    
    # Split the dataset into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_ratio, random_state=42)
    
    # Train the Random Forest Classifier
    svm = SVC()
    svm.fit(X_train,y_train)
    
    # Predict on the test data
    svm_predict = svm.predict(X_test)
    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, svm_predict)
    precision_legit = precision_score(y_test, svm_predict, pos_label=0)*100
    precision_phish = precision_score(y_test, svm_predict, pos_label=1)*100
    recall_legit = recall_score(y_test, svm_predict, pos_label=0)*100
    recall_phish = recall_score(y_test, svm_predict, pos_label=1)*100
    f1_legit = f1_score(y_test, svm_predict, pos_label=0)*100
    f1_phish = f1_score(y_test, svm_predict, pos_label=1)*100
    cm = confusion_matrix(y_test, svm_predict)
    # Convert accuracy to percentage
    accuracy_percentage = accuracy * 100
    
    # Print results for legitimate class
    print("Results for Legitimate class:")
    print("Accuracy:", accuracy_percentage, "%")
    print("Precision:", precision_legit, "%")
    print("Recall:", recall_legit, "%")
    print("F1 Score:", f1_legit, "%")
    print("Confusion Matrix:")
    print(cm)
    print()
    
    # Print results for phishing class
    print("Results for Phishing class:")
    print("Accuracy:", accuracy_percentage, "%")
    print("Precision:", precision_phish, "%")
    print("Recall:", recall_phish, "%")
    print("F1 Score:", f1_phish, "%")
    print("Confusion Matrix:")
    print(cm)
    print()


Test Ratio: 0.1
Results for Legitimate class:
Accuracy: 86.52668416447943 %
Precision: 86.5874363327674 %
Recall: 87.17948717948718 %
F1 Score: 86.88245315161839 %
Confusion Matrix:
[[510  75]
 [ 79 479]]

Results for Phishing class:
Accuracy: 86.52668416447943 %
Precision: 86.46209386281588 %
Recall: 85.84229390681004 %
F1 Score: 86.15107913669064 %
Confusion Matrix:
[[510  75]
 [ 79 479]]

Test Ratio: 0.2
Results for Legitimate class:
Accuracy: 85.34558180227472 %
Precision: 85.6152512998267 %
Recall: 85.39325842696628 %
F1 Score: 85.50411077455647 %
Confusion Matrix:
[[988 169]
 [166 963]]

Results for Phishing class:
Accuracy: 85.34558180227472 %
Precision: 85.07067137809187 %
Recall: 85.29672276350753 %
F1 Score: 85.18354710305175 %
Confusion Matrix:
[[988 169]
 [166 963]]

Test Ratio: 0.3
Results for Legitimate class:
Accuracy: 84.89355497229512 %
Precision: 85.79009433962264 %
Recall: 84.00692840646651 %
F1 Score: 84.88914819136522 %
Confusion Matrix:
[[1455  277]
 [ 241 1456]]


In [21]:
#Decision Tree
test_ratios = [0.1,0.2, 0.3, 0.4,0.5,0.6,0.7,0.8,0.9]

for test_ratio in test_ratios:
    print(f"Test Ratio: {test_ratio}")
    
    # Split the dataset into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_ratio, random_state=42)
    
    # Train the Random Forest Classifier
    decision_tree = DecisionTreeClassifier(criterion="gini") #call model
    decision_tree.fit(X_train,y_train)
    # Predict on the test data
    decision_predict = decision_tree.predict(X_test)
    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, decision_predict )
    precision_legit = precision_score(y_test, decision_predict , pos_label=0)*100
    precision_phish = precision_score(y_test, decision_predict , pos_label=1)*100
    recall_legit = recall_score(y_test,decision_predict , pos_label=0)*100
    recall_phish = recall_score(y_test, decision_predict , pos_label=1)*100
    f1_legit = f1_score(y_test, decision_predict , pos_label=0)*100
    f1_phish = f1_score(y_test, decision_predict , pos_label=1)*100
    cm = confusion_matrix(y_test, decision_predict )
    # Convert accuracy to percentage
    accuracy_percentage = accuracy * 100
    
    # Print results for legitimate class
    print("Results for Legitimate class:")
    print("Accuracy:", accuracy_percentage, "%")
    print("Precision:", precision_legit, "%")
    print("Recall:", recall_legit, "%")
    print("F1 Score:", f1_legit, "%")
    print("Confusion Matrix:")
    print(cm)
    print()
    
    # Print results for phishing class
    print("Results for Phishing class:")
    print("Accuracy:", accuracy_percentage, "%")
    print("Precision:", precision_phish, "%")
    print("Recall:", recall_phish, "%")
    print("F1 Score:", f1_phish, "%")
    print("Confusion Matrix:")
    print(cm)
    print()


Test Ratio: 0.1
Results for Legitimate class:
Accuracy: 94.48818897637796 %
Precision: 93.93939393939394 %
Recall: 95.38461538461539 %
F1 Score: 94.65648854961832 %
Confusion Matrix:
[[558  27]
 [ 36 522]]

Results for Phishing class:
Accuracy: 94.48818897637796 %
Precision: 95.08196721311475 %
Recall: 93.54838709677419 %
F1 Score: 94.3089430894309 %
Confusion Matrix:
[[558  27]
 [ 36 522]]

Test Ratio: 0.2
Results for Legitimate class:
Accuracy: 93.26334208223972 %
Precision: 93.64664926022628 %
Recall: 92.9991356957649 %
F1 Score: 93.32176929748483 %
Confusion Matrix:
[[1076   81]
 [  73 1056]]

Results for Phishing class:
Accuracy: 93.26334208223972 %
Precision: 92.87598944591029 %
Recall: 93.53410097431355 %
F1 Score: 93.20388349514562 %
Confusion Matrix:
[[1076   81]
 [  73 1056]]

Test Ratio: 0.3
Results for Legitimate class:
Accuracy: 93.00087489063867 %
Precision: 93.37209302325581 %
Recall: 92.72517321016166 %
F1 Score: 93.04750869061414 %
Confusion Matrix:
[[1606  126]
 [ 114

In [22]:
#Naive Bayes
test_ratios = [0.1,0.2, 0.3, 0.4,0.5,0.6,0.7,0.8,0.9]

for test_ratio in test_ratios:
    print(f"Test Ratio: {test_ratio}")
    
    # Split the dataset into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_ratio, random_state=42)
    
    # Train the Random Forest Classifier
    naive_bayes = GaussianNB() #call model
    naive_bayes.fit(X_train,y_train)
    # Predict on the test data
    naive_bayes_predict = naive_bayes.predict(X_test)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, naive_bayes_predict)
    precision_legit = precision_score(y_test, naive_bayes_predict, pos_label=0)*100
    precision_phish = precision_score(y_test, naive_bayes_predict, pos_label=1)*100
    recall_legit = recall_score(y_test, naive_bayes_predict, pos_label=0)*100
    recall_phish = recall_score(y_test, naive_bayes_predict, pos_label=1)*100
    f1_legit = f1_score(y_test, naive_bayes_predict, pos_label=0)*100
    f1_phish = f1_score(y_test, naive_bayes_predict, pos_label=1)*100
    cm = confusion_matrix(y_test, naive_bayes_predict)
    # Convert accuracy to percentage
    accuracy_percentage = accuracy * 100
    
    # Print results for legitimate class
    print("Results for Legitimate class:")
    print("Accuracy:", accuracy_percentage, "%")
    print("Precision:", precision_legit, "%")
    print("Recall:", recall_legit, "%")
    print("F1 Score:", f1_legit, "%")
    print("Confusion Matrix:")
    print(cm)
    print()
    
    # Print results for phishing class
    print("Results for Phishing class:")
    print("Accuracy:", accuracy_percentage, "%")
    print("Precision:", precision_phish, "%")
    print("Recall:", recall_phish, "%")
    print("F1 Score:", f1_phish, "%")
    print("Confusion Matrix:")
    print(cm)
    print()


Test Ratio: 0.1
Results for Legitimate class:
Accuracy: 78.91513560804898 %
Precision: 71.88295165394402 %
Recall: 96.58119658119658 %
F1 Score: 82.4215900802334 %
Confusion Matrix:
[[565  20]
 [221 337]]

Results for Phishing class:
Accuracy: 78.91513560804898 %
Precision: 94.39775910364145 %
Recall: 60.39426523297491 %
F1 Score: 73.66120218579235 %
Confusion Matrix:
[[565  20]
 [221 337]]

Test Ratio: 0.2
Results for Legitimate class:
Accuracy: 78.4776902887139 %
Precision: 71.57689811810512 %
Recall: 95.33275713050993 %
F1 Score: 81.76426982950333 %
Confusion Matrix:
[[1103   54]
 [ 438  691]]

Results for Phishing class:
Accuracy: 78.4776902887139 %
Precision: 92.75167785234899 %
Recall: 61.20460584588131 %
F1 Score: 73.74599786552827 %
Confusion Matrix:
[[1103   54]
 [ 438  691]]

Test Ratio: 0.3
Results for Legitimate class:
Accuracy: 79.00262467191601 %
Precision: 72.19298245614036 %
Recall: 95.03464203233256 %
F1 Score: 82.05383848454638 %
Confusion Matrix:
[[1646   86]
 [ 634 

In [23]:
#GBM
test_ratios = [0.1,0.2, 0.3, 0.4,0.5,0.6,0.7,0.8,0.9]

for test_ratio in test_ratios:
    print(f"Test Ratio: {test_ratio}")
    
    # Split the dataset into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_ratio, random_state=42)
    
    # Train the Random Forest Classifier
    GBM= GradientBoostingClassifier()
    GBM.fit(X_train, y_train)    
    
    # Predict on the test data
    gbm_predict = GBM.predict(X_test)
    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test,  gbm_predict)
    precision_legit = precision_score(y_test,  gbm_predict, pos_label=0)*100
    precision_phish = precision_score(y_test,  gbm_predict, pos_label=1)*100
    recall_legit = recall_score(y_test,  gbm_predict, pos_label=0)*100
    recall_phish = recall_score(y_test,  gbm_predict, pos_label=1)*100
    f1_legit = f1_score(y_test, gbm_predict, pos_label=0)*100
    f1_phish = f1_score(y_test,  gbm_predict, pos_label=1)*100
    cm = confusion_matrix(y_test,  gbm_predict)
    # Convert accuracy to percentage
    accuracy_percentage = accuracy * 100
    
    # Print results for legitimate class
    print("Results for Legitimate class:")
    print("Accuracy:", accuracy_percentage, "%")
    print("Precision:", precision_legit, "%")
    print("Recall:", recall_legit, "%")
    print("F1 Score:", f1_legit, "%")
    print("Confusion Matrix:")
    print(cm)
    print()
    
    # Print results for phishing class
    print("Results for Phishing class:")
    print("Accuracy:", accuracy_percentage, "%")
    print("Precision:", precision_phish, "%")
    print("Recall:", recall_phish, "%")
    print("F1 Score:", f1_phish, "%")
    print("Confusion Matrix:")
    print(cm)
    print()


Test Ratio: 0.1
Results for Legitimate class:
Accuracy: 96.8503937007874 %
Precision: 96.92307692307692 %
Recall: 96.92307692307692 %
F1 Score: 96.92307692307692 %
Confusion Matrix:
[[567  18]
 [ 18 540]]

Results for Phishing class:
Accuracy: 96.8503937007874 %
Precision: 96.7741935483871 %
Recall: 96.7741935483871 %
F1 Score: 96.7741935483871 %
Confusion Matrix:
[[567  18]
 [ 18 540]]

Test Ratio: 0.2
Results for Legitimate class:
Accuracy: 95.84426946631672 %
Precision: 96.09375 %
Recall: 95.67847882454625 %
F1 Score: 95.88566478995236 %
Confusion Matrix:
[[1107   50]
 [  45 1084]]

Results for Phishing class:
Accuracy: 95.84426946631672 %
Precision: 95.59082892416225 %
Recall: 96.01417183348096 %
F1 Score: 95.8020326999558 %
Confusion Matrix:
[[1107   50]
 [  45 1084]]

Test Ratio: 0.3
Results for Legitimate class:
Accuracy: 95.74219889180519 %
Precision: 95.99767981438515 %
Recall: 95.55427251732101 %
F1 Score: 95.77546296296295 %
Confusion Matrix:
[[1655   77]
 [  69 1628]]

Resu

In [24]:
#KNN
test_ratios = [0.1,0.2, 0.3, 0.4,0.5,0.6,0.7,0.8,0.9]

for test_ratio in test_ratios:
    print(f"Test Ratio: {test_ratio}")
    
    # Split the dataset into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_ratio, random_state=42)
    
    # Train the Random Forest Classifier
    KNN= KNeighborsClassifier()
    KNN.fit(X_train, y_train)
    # Predict on the test data
    knn_predict = KNN.predict(X_test)
    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, knn_predict)
    precision_legit = precision_score(y_test, knn_predict, pos_label=0)*100
    precision_phish = precision_score(y_test, knn_predict, pos_label=1)*100
    recall_legit = recall_score(y_test, knn_predict, pos_label=0)*100
    recall_phish = recall_score(y_test, knn_predict, pos_label=1)*100
    f1_legit = f1_score(y_test, knn_predict, pos_label=0)*100
    f1_phish = f1_score(y_test, knn_predict, pos_label=1)*100
    cm = confusion_matrix(y_test,knn_predict)
    # Convert accuracy to percentage
    accuracy_percentage = accuracy * 100
    
    # Print results for legitimate class
    print("Results for Legitimate class:")
    print("Accuracy:", accuracy_percentage, "%")
    print("Precision:", precision_legit, "%")
    print("Recall:", recall_legit, "%")
    print("F1 Score:", f1_legit, "%")
    print("Confusion Matrix:")
    print(cm)
    print()
    
    # Print results for phishing class
    print("Results for Phishing class:")
    print("Accuracy:", accuracy_percentage, "%")
    print("Precision:", precision_phish, "%")
    print("Recall:", recall_phish, "%")
    print("F1 Score:", f1_phish, "%")
    print("Confusion Matrix:")
    print(cm)
    print()


Test Ratio: 0.1


C:\Users\RV\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Results for Legitimate class:
Accuracy: 85.21434820647418 %
Precision: 85.98615916955016 %
Recall: 84.95726495726495 %
F1 Score: 85.46861564918315 %
Confusion Matrix:
[[497  88]
 [ 81 477]]

Results for Phishing class:
Accuracy: 85.21434820647418 %
Precision: 84.42477876106194 %
Recall: 85.48387096774194 %
F1 Score: 84.95102404274265 %
Confusion Matrix:
[[497  88]
 [ 81 477]]

Test Ratio: 0.2


C:\Users\RV\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Results for Legitimate class:
Accuracy: 86.61417322834646 %
Precision: 87.68821966341895 %
Recall: 85.56611927398444 %
F1 Score: 86.61417322834644 %
Confusion Matrix:
[[990 167]
 [139 990]]

Results for Phishing class:
Accuracy: 86.61417322834646 %
Precision: 85.56611927398444 %
Recall: 87.68821966341895 %
F1 Score: 86.61417322834644 %
Confusion Matrix:
[[990 167]
 [139 990]]

Test Ratio: 0.3


C:\Users\RV\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Results for Legitimate class:
Accuracy: 86.43919510061242 %
Precision: 87.95686039544638 %
Recall: 84.75750577367207 %
F1 Score: 86.32755072037637 %
Confusion Matrix:
[[1468  264]
 [ 201 1496]]

Results for Phishing class:
Accuracy: 86.43919510061242 %
Precision: 85.0 %
Recall: 88.15556865055981 %
F1 Score: 86.54903095169222 %
Confusion Matrix:
[[1468  264]
 [ 201 1496]]

Test Ratio: 0.4


C:\Users\RV\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Results for Legitimate class:
Accuracy: 86.28608923884514 %
Precision: 87.34177215189874 %
Recall: 84.7740236946029 %
F1 Score: 86.03874415497663 %
Confusion Matrix:
[[1932  347]
 [ 280 2013]]

Results for Phishing class:
Accuracy: 86.28608923884514 %
Precision: 85.29661016949153 %
Recall: 87.78892280854775 %
F1 Score: 86.52482269503547 %
Confusion Matrix:
[[1932  347]
 [ 280 2013]]

Test Ratio: 0.5


C:\Users\RV\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Results for Legitimate class:
Accuracy: 85.7392825896763 %
Precision: 86.58798283261802 %
Recall: 84.6207619713387 %
F1 Score: 85.59307053208414 %
Confusion Matrix:
[[2421  440]
 [ 375 2479]]

Results for Phishing class:
Accuracy: 85.7392825896763 %
Precision: 84.92634463857486 %
Recall: 86.86054660126139 %
F1 Score: 85.88255672960334 %
Confusion Matrix:
[[2421  440]
 [ 375 2479]]

Test Ratio: 0.6


C:\Users\RV\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Results for Legitimate class:
Accuracy: 85.2580927384077 %
Precision: 85.3105681483662 %
Recall: 84.98533724340176 %
F1 Score: 85.14764213309829 %
Confusion Matrix:
[[2898  512]
 [ 499 2949]]

Results for Phishing class:
Accuracy: 85.2580927384077 %
Precision: 85.20658769141866 %
Recall: 85.52784222737819 %
F1 Score: 85.36691272253583 %
Confusion Matrix:
[[2898  512]
 [ 499 2949]]

Test Ratio: 0.7


C:\Users\RV\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Results for Legitimate class:
Accuracy: 84.46444194475691 %
Precision: 84.21448258581809 %
Recall: 84.57473578258681 %
F1 Score: 84.39422473320779 %
Confusion Matrix:
[[3361  613]
 [ 630 3397]]

Results for Phishing class:
Accuracy: 84.46444194475691 %
Precision: 84.71321695760598 %
Recall: 84.35559970201142 %
F1 Score: 84.53403011073785 %
Confusion Matrix:
[[3361  613]
 [ 630 3397]]

Test Ratio: 0.8


C:\Users\RV\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Results for Legitimate class:
Accuracy: 83.51924759405074 %
Precision: 83.10472458088395 %
Recall: 83.92700087950747 %
F1 Score: 83.51383874849579 %
Confusion Matrix:
[[3817  731]
 [ 776 3820]]

Results for Phishing class:
Accuracy: 83.51924759405074 %
Precision: 83.93759613271808 %
Recall: 83.11575282854656 %
F1 Score: 83.52465289165846 %
Confusion Matrix:
[[3817  731]
 [ 776 3820]]

Test Ratio: 0.9


C:\Users\RV\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Results for Legitimate class:
Accuracy: 82.07446291435792 %
Precision: 81.47862918752406 %
Recall: 82.75322643723113 %
F1 Score: 82.11098176173846 %
Confusion Matrix:
[[4232  882]
 [ 962 4211]]

Results for Phishing class:
Accuracy: 82.07446291435792 %
Precision: 82.68211270371097 %
Recall: 81.40344094335975 %
F1 Score: 82.03779466199104 %
Confusion Matrix:
[[4232  882]
 [ 962 4211]]



In [ ]:
#From these we conclude that Random Forest is giving the higher accuracy. so Random Forest is further used for detection of url
